/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libharu_Document */

#ifndef _Included_org_libharu_Document
#define _Included_org_libharu_Document
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libharu_Document
 * Method:    setCompressionMode
 * Signature: (Lorg/libharu/Document/CompressionMode;)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Document_setCompressionMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libharu_Document
 * Method:    setPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Document_setPassword
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_libharu_Document
 * Method:    saveToFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Document_saveToFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libharu_Document
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Document_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_libharu_Document
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Document_construct
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_Document
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Document_destruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
