/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libharu_Document_CompressionMode */

#ifndef _Included_org_libharu_Document_CompressionMode
#define _Included_org_libharu_Document_CompressionMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
