/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libharu_Font */

#ifndef _Included_org_libharu_Font
#define _Included_org_libharu_Font
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libharu_Font
 * Method:    construct
 * Signature: (Lorg/libharu/Document;Lorg/libharu/Font/BuiltinFont;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Font_construct
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     org_libharu_Font
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Font_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
