/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libharu_Page */

#ifndef _Included_org_libharu_Page
#define _Included_org_libharu_Page
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libharu_Page
 * Method:    setSize
 * Signature: (Lorg/libharu/Page/PageSize;Lorg/libharu/Page/PageDirection;)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_setSize
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    getHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_libharu_Page_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    getWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_libharu_Page_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    setLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_setLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_libharu_Page
 * Method:    setLineCap
 * Signature: (Lorg/libharu/Page/LineCap;)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_setLineCap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    setLineJoin
 * Signature: (Lorg/libharu/Page/LineJoin;)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_setLineJoin
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    setMiterLimit
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_setMiterLimit
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_libharu_Page
 * Method:    setRGBStroke
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_setRGBStroke
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_libharu_Page
 * Method:    setRGBFill
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_setRGBFill
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_libharu_Page
 * Method:    moveTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_moveTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_libharu_Page
 * Method:    lineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_lineTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_libharu_Page
 * Method:    curveTo
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_curveTo
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_libharu_Page
 * Method:    stroke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_stroke
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    fill
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_fill
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    fillStroke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_fillStroke
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    image
 * Signature: (Lorg/libharu/Image;FFFF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_image
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_libharu_Page
 * Method:    beginText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_beginText
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    endText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_endText
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    getTextWidth
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_org_libharu_Page_getTextWidth
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libharu_Page
 * Method:    setFontAndSize
 * Signature: (Lorg/libharu/Font;F)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_setFontAndSize
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     org_libharu_Page
 * Method:    textOut
 * Signature: (FFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_textOut
  (JNIEnv *, jobject, jfloat, jfloat, jstring);

/*
 * Class:     org_libharu_Page
 * Method:    moveTextPos
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_moveTextPos
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_libharu_Page
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_libharu_Page
 * Method:    construct
 * Signature: (Lorg/libharu/Document;)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_construct
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_libharu_Page
 * Method:    destruct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Page_destruct
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
