/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libharu_Image */

#ifndef _Included_org_libharu_Image
#define _Included_org_libharu_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libharu_Image
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_Image_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_libharu_Image
 * Method:    construct
 * Signature: (Lorg/libharu/Document;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_libharu_Image_construct
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
