/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libharu_Font_BuiltinFont */

#ifndef _Included_org_libharu_Font_BuiltinFont
#define _Included_org_libharu_Font_BuiltinFont
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
