/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libharu_Page_PageSize */

#ifndef _Included_org_libharu_Page_PageSize
#define _Included_org_libharu_Page_PageSize
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
